### ISSUE TITLE
GPU support for plugins

### ISSUE THREAD

**Issue by ktaletsk** [usnistgov/WIPP-backend#109]
**Description**

To get access to GPU in Kubernetes, pods need to have a special tag added to their spec (https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/#deploying-nvidia-gpu-device-plugin). That means it is something plugin authors can't enable from within container, WIPP needs to use a slightly different Argo Workflow .yaml (https://github.com/argoproj/argo/issues/577)

**Proposal**

- Add a new field to plugin manifest with an option to request of GPU resources, i.e. `gpu`
- If option is chosen in plugin manifest, WIPP-backend will add the following lines to Argo Workflow .yaml container spec:
```
resources:
        limits:
          nvidia.com/gpu: 1
```
(number of GPUs should be a configurable workflow parameter)

**Comment by MyleneSimon** [comment]
So we are currently getting back on this issue, after some discussion with our acceleration team, they suggested that we should be more specific than just "gpu true/false", and include card vendor and other requirements for the plugin to run, for example:
```json
"gpu":
    "nvidia":
        "computeCapabilities": "5",
        "cudaVersion": "10.1"
```
What do you think of that approach @ktaletsk and @sunnielyu regarding the clusters that you are dealing with? Would that work in terms of labeling the nodes?

**Comment by MyleneSimon** [comment]
Discussion moved to more general discussion about hardware requirements mapping: https://github.com/usnistgov/WIPP/issues/27
