### ISSUE TITLE
Support upload of CSV collection

### ISSUE THREAD

**Issue by MyleneSimon** [usnistgov/WIPP-backend#110]
**Description**
Add the capability to create a new `csvCollection` by uploading a set of CSV files, similar to the way users can create new Stitching vectors.

**Proposal**
Create a `CsvCollectionUploadController` with an `upload` method that will accept a string (desired name for the collection) and array of files (`MultipartFile[] files`), and return the newly created `CsvCollection` or an error if the name is empty or already taken.

**Additional context**
Current restriction regarding file size is 5Mb/per file, 30Mb/request, so we should up the request limit to 50 or 100Mb. For this first implementation, upload of large collections of large files will not be supported.

**Comment by pbajcsy** [comment]
Current request to address this issue: Creating/Uploading CSV collections to WIPP where each csv file is <1MB in size
Future request to address this issue: Creating/Uploading CSV collections to WIPP where each csv file is >100GB in size

**Comment by MyleneSimon** [comment]
Chunk upload as been implemented with #120 and https://github.com/usnistgov/WIPP-frontend/pull/144
