### ISSUE TITLE
Support export of collections from Catalog to WIPP

### ISSUE THREAD

**Issue by MyleneSimon** [usnistgov/WIPP-backend#111]
**Description**
The NCATS team is developing the Catalog app, where users can upload collections of images, visualize them , reorganize them and more. User should be able to export set of images from Catalog to WIPP, so that he can then run computations on them.

**Proposal**
The support of this feature is divided in several steps:
1. Decouple submission to the OME TIFF conversion from the image upload
Currently, the methods for submitting uploaded images to the OME TIFF conversion are inside of the `ImageUploadController` class, but in order to support multiple ways of creating image collections, we should put them in their own class.
**To do**: 
    - Create new class `ImageConversionService` (annotated with `@Service`) in the same package, and move methods `submitImageToExtractor`, `doSubmit` and `convertToTiledOmeTiff` in this new class.

2. Add new `importMethod` and `sourceCatalog` attribute to the `ImagesCollection` class
Since we are extending the ways images collections can be created, we need to record the method that was used and keep track of the source.
**To do**: 
    - Create new `ImagesCollectionImportMethod` enum with the following values: `UPLOADED`, `JOB` and `CATALOG`, add `importMethod` attribute to `ImagesCollection`
    - Add `sourceCatalog` (string) attribute to `ImagesCollection`
    - Modify existing `ImagesCollection` constructors to accommodate for the new `importMethod` field
(`public ImagesCollection(String name, boolean locked)` should now become `public ImagesCollection(String name, boolean locked, ImagesCollectionImportMethod importMethod)`)
    - Create new constructor for collections created from Catalog
`public ImagesCollection(String name, String sourceCatalog)` that will set name and creation date, as well as `locked` to true (users should not upload images to a collection coming from catalog), `sourceCatalog` to sourceCatalog and `importMethod` to `ImagesCollectionImportMethod.CATALOG`

3. Create `ImagesCollectionCatalogImportController` class 
**To do**: 
    - Create new `ImagesCollectionCatalogImportController` that will import files from the images collection temp folder, with OME TIFF conversion of the images (a bit similar to the `importData` method of `ImagesCollectionDataHandler`, but with an added step for the conversion). Before running the import, the first step should be to check that: the collection is empty, the `importMethod` is `CATALOG`, and `sourceCatalog` is not empty.

**Additional context**
Export images from Catalog to WIPP flow:
1. Create new WIPP Images Collection from Catalog (using the REST API, specifying desired name for the collection, as well as ID of the Catalog resource), this will return the newly created collection, including ID
2. Copy of files from Catalog to the temp folder of the collection 
3. Once copy is done, request to the `ImagesCollectionCatalogImportController`, which will trigger the import of the files in the collection (physical import to the proper folders, as well as conversion to OME TIFF and update of the metadata in the database)

**Comment by pbajcsy** [comment]
Note: It would be useful to post the list of the REST APIs that are offered in WIPP 3.0 (and needed for addressing this issue).  The URL of the posted list would become available to all WIPP developers.
