### ISSUE TITLE
Convert WIPP 3.0 plugin for converting WDZT annotations to masks

### ISSUE THREAD

**Issue by pbajcsy** [usnistgov/WIPP-backend#16]
**Description**
(Include problem, use cases, benefits, and/or goals)
Problem: Users can create image annotations using the WDZT visualization and download a JSON file per image. However, users cannot use the annotated images for AI model training unless a plugin for converting annotations to image masks is available.
Use cases: AI-based segmentation for RPE cells, concrete samples, and organelle videos cannot be executed unless the manual annotations provided by experts are converted to training image masks.
Benefits: users will be able to annotate and train AI-based models in WIPP 3.0
Goals: create a WIPP 3.0 plugin that takes a collection of JSON files (annotations from a collection of images) and generates a collection of image masks. The plugin will have user-specified options whether the masks should follow color, text, or shape attributes of annotations when assigning semantic labels. 

**Proposal**
(A clear and concise description of what you want to happen)
Create a WIPP 3.0 plugin with the conversion code. 

**Additional context**
(Add any other context or screenshots about the feature request here)
Starting point is in https://gitlab.nist.gov/gitlab/WIPP/WIPP-annotation2mask-plugin

**Comment by MyleneSimon** [comment]
Plugin is available here: https://github.com/usnistgov/WIPP-annotations2masks-plugin
Support for annotations in WIPP in #133
