### ISSUE TITLE
Add authorization to Swagger API docs

### ISSUE THREAD

**Issue by ktaletsk** [usnistgov/WIPP-backend#175]
**Description**
Currently, Swagger OpenAPI description generated by WIPP-backend is not aware of Keycloak authorization required in the latest version to access most of the API endpoints.

**Proposal**
Add required annotations to the API methods protected by Keycloak.

**Additional context**
Providing accurate API documentation in Swagger would allow automatic API client generation with `swagger-codegen`.

**Comment by MyleneSimon** [comment]
I looked at the doc of library we are using, it seems that I can add a `SecurityScheme` to the Swagger conf to enable SSO from the UI, I will give it a try later this week.
