### ISSUE TITLE
Why is creation of Generic Data via REST API not allowed?

### ISSUE THREAD

**Issue by ktaletsk** [usnistgov/WIPP-backend#183]
**Question**

I can create Image and CSV collections via API call. But, when I'm trying to create a Generic Data collection, I'm getting HTTP error 400 with message "Creation of Generic Data via REST API is not allowed".

https://github.com/usnistgov/WIPP-backend/blob/f04c3e254325cb70d394c032b9773f88e952555d/wipp-backend-data/src/main/java/gov/nist/itl/ssd/wipp/backend/data/genericdata/GenericDataEventHandler.java#L48

Is there any way to handle Generic Data collections through API? Or are they only meant to be generated by Workflows?

**Comment by MyleneSimon** [comment]
This was supposed to be added by #155 (or that one would be closed and a new fresh one opened). @mohamedOuladi, do you have an ETA for the new PR?

**Comment by mohamedOuladi** [comment]
@MyleneSimon Oh my bad! I've worked on it a while ago and thought I've submitted the PR. Just created a new one here #184. I'll close the old one.

**Comment by MyleneSimon** [comment]
:smile: I just saw the new PR, I will try to get to it on Friday or early next week.

**Comment by ktaletsk** [comment]
Thanks @MyleneSimon @mohamedOuladi, sorry to bother you so much with my issues and PRs. Currently testing API client and noticing all of these issues.

**Comment by MyleneSimon** [comment]
No worries at all @ktaletsk, and I am wrapping up some changes for the upcoming release, so it is actually a good timing to include a few small fixes.

**Comment by MyleneSimon** [comment]
Feature added in #184, closing the issue.
